[package]
name = "neon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
lazy_static = "1.4.0"
tracing = "0.1.40"
tracing-attributes = { version = "0.1.27", features = [] }
tracing-subscriber = "0.3.18"
env_logger = "0.11.3"
log = "0.4.21"

[features]
disassemble = []